"""Where uploaded files live.

Two implementations: the database (today — there is no object storage account yet) and S3-compatible
storage (Scaleway, and anything else that speaks S3). The port exists so the second one is a
configuration change rather than a rewrite: nothing above this line knows where the bytes are.

Keys are opaque and generated by the caller; a store never invents one, and never guesses a tenant.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable
from uuid import UUID

from app.core.errors import DomainError, NotFound


class DocumentTooLarge(DomainError):
    status = 413
    code = "DOCUMENT_TOO_LARGE"


class UnsupportedDocumentType(DomainError):
    status = 415
    code = "UNSUPPORTED_DOCUMENT_TYPE"


class DocumentStoreUnavailable(DomainError):
    status = 502
    code = "DOCUMENT_STORE_UNAVAILABLE"


class DocumentNotFound(NotFound):
    def __init__(self, key: str) -> None:
        super().__init__(f"Document {key}")


@runtime_checkable
class DocumentStore(Protocol):
    name: str

    def put(self, org_id: UUID, key: str, content: bytes, content_type: str) -> None: ...

    def get(self, org_id: UUID, key: str) -> bytes:
        """Raise `DocumentNotFound` when the key is unknown to this organization."""
        ...

    def delete(self, org_id: UUID, key: str) -> None:
        """Deleting something that is not there is not an error."""
        ...
